<%
DIM tclass
%><a<%if menuid=4 then response.write " class=""topmenusel"""%> id="t4" href="javascript:;" onMouseOver="P7_Snap('t4','closer',topmenu_xoffset-8,topmenu_yoffset,'t4','d4',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d4','closer');">Introduktion</a>
<a<%if menuid=7 then response.write " class=""topmenusel"""%> id="t7" href="javascript:;" onMouseOver="P7_Snap('t7','closer',topmenu_xoffset-8,topmenu_yoffset,'t7','d7',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d7','closer');">BU Internationalt</a>
<a<%if menuid=8 then response.write " class=""topmenusel"""%> id="t8" href="javascript:;" onMouseOver="P7_Snap('t8','closer',topmenu_xoffset-8,topmenu_yoffset,'t8','d8',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d8','closer');">BU i Danmark</a>
<a<%if menuid=9 then response.write " class=""topmenusel"""%> id="t9" href="javascript:;" onMouseOver="P7_Snap('t9','closer',topmenu_xoffset-8,topmenu_yoffset,'t9','d9',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d9','closer');">Agenda 21</a>
<a<%if menuid=10 then response.write " class=""topmenusel"""%> id="t10" href="javascript:;" onMouseOver="P7_Snap('t10','closer',topmenu_xoffset-8,topmenu_yoffset,'t10','d10',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d10','closer');">Indikatorer</a>
<a<%if menuid=11 then response.write " class=""topmenusel"""%> id="t11" href="javascript:;" onMouseOver="P7_Snap('t11','closer',topmenu_xoffset-8,topmenu_yoffset,'t11','d11',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d11','closer');">Temaer</a>
<a<%if menuid=12 then response.write " class=""topmenusel"""%> id="t12" href="javascript:;" onMouseOver="P7_Snap('t12','closer',topmenu_xoffset-8,topmenu_yoffset,'t12','d12',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d12','closer');">Uddannelse </a>
<a<%if menuid=13 then response.write " class=""topmenusel"""%> id="t13" href="javascript:;" onMouseOver="P7_Snap('t13','closer',topmenu_xoffset-8,topmenu_yoffset,'t13','d13',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d13','closer');">Aktuelt</a>
<a<%if menuid=14 then response.write " class=""topmenusel"""%> id="t14" href="javascript:;" onMouseOver="P7_Snap('t14','closer',topmenu_xoffset-8,topmenu_yoffset,'t14','d14',topmenu_xoffset,topmenu_yoffset);P7_autoLayers(0,'d14','closer');">Ressourcer</a>
